Feature lottie animation
GatienBancarel/AdoptYourPet pull request #12
Opened 2020-08-19 12:34 UTC by GatienBancarel

2020-08-19 12:52 UTC, paul1893 requested changes

2020-08-19 12:52 UTC, paul1893 commented on app/src/main/java/com/gbancarel/adoptyourpet/controller/HomePageController.kt
> +    @RequiresApi(Build.VERSION_CODES.M)
? Tu target Android API minimum 21 c'est à dire Lollipop (cf ton build.gradle). Donc tu peux pas demander Android M ici (car Android Marshmallow > Android Lollipop)

2020-08-19 12:52 UTC, paul1893 commented on app/src/main/java/com/gbancarel/adoptyourpet/controller/HomePageController.kt
> +    @RequiresApi(Build.VERSION_CODES.M)
Il faut trouver comment se passer de cette annotation ;)

2020-08-19 12:52 UTC, paul1893 commented on app/src/main/java/com/gbancarel/adoptyourpet/controller/HomePageController.kt
> +    @RequiresApi(Build.VERSION_CODES.M)
Idem. Il faut trouver comment se passer de cette annotation ;)

2020-08-19 12:52 UTC, paul1893 commented on app/src/main/java/com/gbancarel/adoptyourpet/interactor/HomePageInteractor.kt
> +    @RequiresApi(Build.VERSION_CODES.M)
Idem :D. Il faut trouver comment se passer de cette annotation ;)

2020-08-19 12:52 UTC, paul1893 commented on app/src/main/java/com/gbancarel/adoptyourpet/interactor/HomePageInteractor.kt
> +            val listAnimal = repository.getListAnimal()
Bcp plus clair top +1

2020-08-19 12:52 UTC, paul1893 commented on app/src/main/java/com/gbancarel/adoptyourpet/presenter/HomePagePresenter.kt
> +            error = true,
Plutôt que d'avoir plusieurs boolean ce qui peut porter à confusion si par exemple au fur et à mesure que l'équipe code vs vs retrouvez avec un PetFinderViewModel qui a `error = true` et `loader = true`. Ce qui n'a pas vrmt de sens.

Tu peux utiliser les enum qui sont fait pour ce genre chose. Moi je verrais bien:

```
enum class PetFinderViewModelState {
  case finished, error, loading
}

et du coup ton PetFinderViewModel devient:

data class PetFinderViewModel(
  val state: PetFinderViewModelState
  val animals: List<PetAnimalViewModel>
)

et ton activity:

when (data.value.state) {
  error -> {
    val bindingLoader = LoaderBinding.inflate(layoutInflater)
    setContentView(bindingLoader.root)
  }
  loading -> {
     val bindingError = ErrorBinding.inflate(layoutInflater)
     setContentView(bindingError.root)
  }
  finished -> {
       setContent{
            HomePage().Page(applicationContext,data)
       }
    }
}



```

2020-08-19 12:52 UTC, paul1893 commented on app/src/main/java/com/gbancarel/adoptyourpet/repository/HomePageRepository.kt
> +    @RequiresApi(Build.VERSION_CODES.M)
Idem

2020-08-19 12:52 UTC, paul1893 commented on app/src/main/java/com/gbancarel/adoptyourpet/repository/service/PetFinderService.kt
> +    @RequiresApi(Build.VERSION_CODES.M)
Idem

2020-08-19 12:52 UTC, paul1893 commented on app/src/main/java/com/gbancarel/adoptyourpet/repository/service/PetFinderService.kt
> +            return ResponseRequest(
C'est pas une erreur 500 le serveur est disponible c'est juste que ton device ne capte pas ou est en mode avion. Ici pas de response, throw une exception c'est la faute du device si ça ne marche pas.

`throw NoInternetConnectionAvailable` ou un truc du style comme on a fait pour le parsing du JSON

2020-08-19 12:52 UTC, paul1893 commented
Supprime chien.png ou dog.JPG dans `drawable-v24` si tu ne t'en sers plus. (J'ai l'impression que c'est le cas).

2020-08-19 12:55 UTC, paul1893 commented on app/src/main/java/com/gbancarel/adoptyourpet/controller/HomePageController.kt
> +        interactor.getListAnimal()
Les T.U fêtent car tu as laissé `getCall`

2020-08-19 12:55 UTC, paul1893 commented on app/src/main/java/com/gbancarel/adoptyourpet/interactor/HomePageInteractor.kt
> +            val listAnimal = repository.getListAnimal()
Idem T.U prêtent à cause du nom non modifié

2020-08-19 12:56 UTC, paul1893 commented on app/src/main/java/com/gbancarel/adoptyourpet/presenter/HomePagePresenter.kt
> +            error = true,
Pense à faire les T.U

2020-08-19 13:07 UTC, paul1893 commented on app/src/main/java/com/gbancarel/adoptyourpet/repository/service/PetFinderService.kt
> +    @RequiresApi(Build.VERSION_CODES.M)
```
fun isOnline(context: Context): Boolean {
    val connectivityManager = context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) { 
        val capabilities = connectivityManager.getNetworkCapabilities(connectivityManager.activeNetwork)
        if (capabilities != null) {
            when {
                capabilities.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR) -> {
                    return true
                }
                capabilities.hasTransport(NetworkCapabilities.TRANSPORT_WIFI) -> {
                    return true
                }
                capabilities.hasTransport(NetworkCapabilities.TRANSPORT_ETHERNET) -> {
                    return true
                }
            }
        }
    } else {
        val activeNetworkInfo = connectivityManager.activeNetworkInfo
        if (activeNetworkInfo != null && activeNetworkInfo.isConnected) {
            return true
        }
    }
    return false
}
```

2020-08-19 17:43 UTC, GatienBancarel commented on app/src/main/java/com/gbancarel/adoptyourpet/controller/HomePageController.kt
> +    @RequiresApi(Build.VERSION_CODES.M)
Je peux les enlever, ça souligne en rouge mais ca compile 🙄

2020-08-19 17:44 UTC, paul1893 commented on app/src/main/java/com/gbancarel/adoptyourpet/controller/HomePageController.kt
> +    @RequiresApi(Build.VERSION_CODES.M)
Non ça crashera sur lollipop

2020-08-19 17:44 UTC, paul1893 commented on app/src/main/java/com/gbancarel/adoptyourpet/controller/HomePageController.kt
> +    @RequiresApi(Build.VERSION_CODES.M)
Il faut gerer tte les versions cf mon autre commentaire

2020-08-20 07:19 UTC, GatienBancarel commented on app/src/main/java/com/gbancarel/adoptyourpet/repository/service/PetFinderService.kt
> +    @RequiresApi(Build.VERSION_CODES.M)
c'est la solution pour enlever l'annotation "@RequiresApi(Build.VERSION_CODES.M)" ? parce que ton else passe pas, c'est obsolète.
![image](https://user-images.githubusercontent.com/56867268/90729055-3d6a4c80-e2c6-11ea-995c-13b6e88ace88.png)

2020-08-20 07:35 UTC, paul1893 commented on app/src/main/java/com/gbancarel/adoptyourpet/repository/service/PetFinderService.kt
> +    @RequiresApi(Build.VERSION_CODES.M)
`Deprecated` bien qu'obsolète ne veut pas dire qu'on ne peut pas l'utiliser. Pour gérer ttes les versions d'Android on est obligé. Jusqu'à ce que la population migre vers des versions plus récentes.

Pas d'autres choix que de faire ça puis un jour l'api sera supprimé définitivement supprimé par Google et on pourra supprimer notre else.

2020-08-20 07:37 UTC, GatienBancarel commented on app/src/main/java/com/gbancarel/adoptyourpet/repository/service/PetFinderService.kt
> +    @RequiresApi(Build.VERSION_CODES.M)
okay donc je laisse comme ca ?

2020-08-20 07:37 UTC, GatienBancarel commented on app/src/main/java/com/gbancarel/adoptyourpet/repository/service/PetFinderService.kt
> +    @RequiresApi(Build.VERSION_CODES.M)
je savais pas, bonne info

2020-08-20 07:39 UTC, paul1893 commented on app/src/main/java/com/gbancarel/adoptyourpet/repository/service/PetFinderService.kt
> +    @RequiresApi(Build.VERSION_CODES.M)
Par contre je me suis pt un peu tromper. En relisant la doc ce matin je vois:
```
getNetworkInfo (Added in API level | Deprecated in API level 23)

This method was deprecated in API level 23.
This method does not support multiple connected networks of the same type. Use getAllNetworks() and getNetworkInfo(android.net.Network) instead.
```
https://developer.android.com/reference/android/net/ConnectivityManager#getNetworkInfo(int)

du coup ce serait plutôt :
`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M)` au lieu de `if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q)`

2020-08-20 07:48 UTC, paul1893 commented on app/src/main/java/com/gbancarel/adoptyourpet/repository/service/PetFinderService.kt
> +    @RequiresApi(Build.VERSION_CODES.M)
Pour rappel:
Android LOLLIPOP = Android 21 = Lollipop 5.0
Android LOLLIPOP_MR1 = Android 22 = Lollipop 5.1
Android M = Android 23 = Marshmallow 6.0
Android N = Android 24 = Nougat 7.0
Android N_MR1 = Android 25 = Nougat 7.1
Android O = Android 26 = Oreo 8.0
Android O_MR1 = Android 27 = Oreo 8.1
Android P = Android 28 = Pie 9.0
Android Q = Android 29 = Android 10
Prochainement Android 11 ...

2020-08-20 09:44 UTC, paul1893 approved these changes

2020-08-20 09:45 UTC, merged